######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 11 20:57:45 2013
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += lab01_2.pro
