
import java.awt.*;
import java.awt.event.*;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author i1macura
 */
public class PanelRadar extends javax.swing.JPanel {

    /**
     * Creates new form PanelRadar
     */
    public PanelRadar() {
        initComponents();
        
    }
    public void setParent(MainFrame rodzic)
    {
        this.rodzic=rodzic;
        Thread timer=new Thread(new Runnable()
        {
            public void run() {
                while(true){
                r=PanelRadar.this.rodzic.getR();
                PanelRadar.this.repaint(); 
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) {
                    Logger.getLogger(PanelRadar.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
                
            }
        });
        timer.start();
    }
    public void paint(Graphics g)
    {
        Graphics2D g2=(Graphics2D)g;
        g2.setBackground(Color.BLACK);
        g2.clearRect(0, 0, this.getWidth(), this.getHeight());
        t+=Math.PI/6;
        int x=this.getWidth()/2;
        int y=this.getHeight()/2;
        double x2=Math.cos(t)*r/2+x;
        double y2=Math.sin(t)*r/2+y;
        g2.setColor(Color.green);
        g2.draw(new Ellipse2D.Double(x-r/2,y-r/2,r,r));
        g2.draw(new Line2D.Double(x, y, x2, y2));
    }
    private MainFrame rodzic;
    private int r;
    private double t=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
